"""Every client-facing Word file must carry deliberate authorship metadata.

python-docx stamps `author = "python-docx"` and `comments = "generated by
python-docx"` into every document it creates, and Word -- when a writer reopens
a file to bake TOC/page fields -- stamps the *Windows account name* into
`last_modified_by`. Both are readable by any recipient via File > Info, so both
were leaking on documents sent to clients. These tests cover all four writers so
a new one, or a refactor, cannot silently reintroduce it.
"""

import getpass

import pytest
from docx import Document

from orchestrator.generation.clarification_sheet_writer import build_sheet
from orchestrator.generation.docx_report_writer import build_report as build_analysis_report
from orchestrator.generation.report_exporter import ReportOptions
from orchestrator.generation.report_exporter import build_document as build_exported_report
from orchestrator.generation.test_plan_docx_writer import _document_author
from orchestrator.models.requirement import Gap, Requirement
from orchestrator.utils.docx_helpers import scrub_authorship, set_authorship

TOOLCHAIN_NAME = "python-docx"


def _properties_blob(document: Document) -> str:
    p = document.core_properties
    return "|".join(
        str(value or "")
        for value in (p.author, p.last_modified_by, p.comments, p.title, p.subject, p.keywords)
    )


def _assert_clean(document: Document) -> None:
    blob = _properties_blob(document)
    assert TOOLCHAIN_NAME not in blob, f"toolchain name leaked into metadata: {blob}"
    assert getpass.getuser() not in blob, f"Windows account name leaked into metadata: {blob}"
    assert document.core_properties.author, "author must be set to something deliberate"


def _requirement() -> Requirement:
    return Requirement(
        req_id="REQ-001",
        requirement_text="The system shall let a user sign in.",
        gaps=[Gap(description="Lockout policy is unstated.", question="After how many failed attempts should the account lock?", blocking=True)],
        acceptance_criteria_status="Not Generated – Client Clarification Required",
        acceptance_criteria="Blocked by the lockout question.",
    )


def test_requirement_analysis_report_metadata_is_deliberate():
    document = build_analysis_report([_requirement()], doc_name="Requirements")
    _assert_clean(document)
    assert document.core_properties.author == "Emvigo QA"
    assert "Requirements" in document.core_properties.title


def test_clarification_sheet_metadata_is_deliberate():
    """The sheet is emailed straight to the client -- the most exposed of the
    four deliverables."""
    rows = [("REQ-001", "The system shall let a user sign in.", "After how many failed attempts should the account lock?")]
    document = build_sheet(rows, doc_name="Requirements")
    _assert_clean(document)
    assert document.core_properties.author == "Emvigo QA"


def test_security_report_metadata_is_deliberate():
    options = ReportOptions(cover_title="Mobile Application Security Assessment", prepared_by="Emvigo QA")
    document = build_exported_report("# Report\n\nBody.\n", options)
    _assert_clean(document)


@pytest.mark.parametrize(
    "prepared_by,expected",
    [
        ("Emvigo Technologies", "Emvigo Technologies"),
        ("", "Emvigo QA"),
        ("   ", "Emvigo QA"),
        # A TBD placeholder is honest inside the document, where a reader sees an
        # unfilled field -- but meaningless as a file author.
        ("TBD – To be added by QA", "Emvigo QA"),
        ("TBD – Client/Project Input Required", "Emvigo QA"),
    ],
)
def test_test_plan_author_prefers_prepared_by_but_never_a_tbd(prepared_by, expected):
    class _Meta:
        pass

    class _Plan:
        pass

    plan = _Plan()
    plan.meta = _Meta()
    plan.meta.prepared_by = prepared_by

    assert _document_author(plan) == expected


def test_set_authorship_clears_the_python_docx_defaults():
    document = Document()
    assert TOOLCHAIN_NAME in _properties_blob(document), (
        "python-docx no longer stamps its own name; this test's premise is stale"
    )

    set_authorship(document, author="Emvigo QA", title="T", subject="S")

    _assert_clean(document)
    assert document.core_properties.comments == ""


def test_scrub_authorship_resets_a_saved_file_and_keeps_title(tmp_path):
    """This is what runs after Word's field-baking save overwrites
    last_modified_by with the Windows account name."""
    path = tmp_path / "sample.docx"
    document = Document()
    set_authorship(document, author="Emvigo QA", title="Test Plan for Acme", subject="PRJ-1")
    document.save(str(path))

    # Simulate Word's save stamping the account name in.
    touched = Document(str(path))
    touched.core_properties.last_modified_by = getpass.getuser()
    touched.save(str(path))
    assert getpass.getuser() in _properties_blob(Document(str(path)))

    scrub_authorship(path, author="Emvigo QA")

    reloaded = Document(str(path))
    _assert_clean(reloaded)
    # The scrub must not wipe the title/subject it didn't set.
    assert reloaded.core_properties.title == "Test Plan for Acme"
    assert reloaded.core_properties.subject == "PRJ-1"
